### ISSUE TITLE
Build-error fix needed: SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by santeriv** [santeriv/pulljson#4]
See latest build result

/home/travis/build/santeriv/pulljson/node_modules/mocha/bin/mocha:13
const {deprecate} = require('../lib/utils');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
Makefile:3: recipe for target 'test' failed
make: *** [test] Error 8
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
cache.2
store build cache

**Comment by santeriv** [comment]
build result here: https://travis-ci.org/santeriv/pulljson

Feel free to change anything to solve it, even funny solutions although secure and not harmful are ok.
